name: Validate Mod Data

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'mods.json'
  push:
    branches: [ main ]
    paths:
      - 'mods.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON Schema against Data
        run: npx -y ajv-cli validate -s mods.schema.json -d mods.json
